In [8]:
"""
This notebook comes after Initial_Heart_Rate_Investigations.
It takes in data that has already been formatted in format_data.py
"""

import sys

import pandas as pd
import tensorflow as tf
import tensorflow_probability as tfp

sys.path.append("/Users/kmcmanus/Documents/classes/algorithm_practice/weather_data_explorations/src")
from baum_welch_alg import BaumWelch

In [9]:
fn = "/Users/kmcmanus/Documents/classes/digitalhealth_project/data/formatted_data/20200308_hr_sleep.csv"
df = pd.read_csv(fn, index_col=0)
df.head()

bpm  confidence             datetime  fb_sleep
2020-01-12 16:06:38   70           0  2020-01-12 16:06:38         1
2020-01-12 16:06:48   70           1  2020-01-12 16:06:48         1
2020-01-12 16:07:03   70           1  2020-01-12 16:07:03         1
2020-01-12 16:07:08   71           1  2020-01-12 16:07:08         1
2020-01-12 16:07:18   73           1  2020-01-12 16:07:18         1

In [10]:
# Run my own Baum Welch algorithm on this.
observations = tf.constant(df['bpm'].iloc[0:5000], dtype=tf.float32, name='observation_sequence')
num_steps = len(observations)
print(num_steps)

tfd = tfp.distributions
initial_distribution = tfd.Categorical(probs=[0.66, 0.33])

transition_distribution = tfd.Categorical(probs=[[0.9, 0.1],
                                                 [0.1, 0.9]])

observation_distribution = tfd.Normal(loc=[63., 80.], scale=[3., 10.])

model = BaumWelch(initial_distribution=initial_distribution,
                  observation_distribution=observation_distribution,
                  transition_distribution=transition_distribution,
                  num_steps=num_steps,
                  epsilon=0.02,
                  maxStep=50,
                  log_dir='.')

441384
Instructions for updating:
The `num_categories` property is deprecated.  Use `tf.shape(self.probs if self.logits is None else self.logits)[-1]` instead.


In [ ]:
initial_dist, trans_dist, observ_dist = model.run_Baum_Welch_EM(observations, summary=False, monitor_state_1=True)

NEW T0
tf.Tensor([0.11920291 0.880797  ], shape=(2,), dtype=float32)
NEW TRANSITION
tf.Tensor(
[[9.994629e-01 5.370895e-04]
 [9.758372e-02 9.024163e-01]], shape=(2, 2), dtype=float32)
NEW EMISSION
means tf.Tensor(inf, shape=(), dtype=float32)
tf.Tensor([inf inf], shape=(2,), dtype=float32)
tf.Tensor([nan nan], shape=(2,), dtype=float32)
tf.Tensor(1.6690817, shape=(), dtype=float32)
